#!/usr/bin/env bash
LAST_UPDATE_FILE="/etc/apt/last-update"
if [ -f ${LAST_UPDATE_FILE} -a -s ${LAST_UPDATE_FILE} -a -r ${LAST_UPDATE_FILE} ]; then
    if [ $(cat ${LAST_UPDATE_FILE}) -ge $(date +%s) ]; then
        exit 0
    fi
fi

echo "Updating apt-key for puppetlabs"
apt-key adv --recv-keys --keyserver keys.gnupg.net 4BD6EC30 >/dev/null || exit $?
apt-key adv --recv-keys --keyserver keys.gnupg.net 7F438280EF8D349F >/dev/null || exit $?

echo "Running apt-get update"
apt-get -y -qq update >/dev/null || exit $?
date --date="00:00:00 tomorrow" +%s > ${LAST_UPDATE_FILE}
