#!/bin/bash

set -e

CHECK_FILE="/etc/vagrant-provisioned"
PROVISION_REQUIRED=0

if [ ! -e ${CHECK_FILE} ]; then
    PROVISION_REQUIRED=2
else
    NOW=$(date +%s)
    NEXT_UPDATE=$(cat ${CHECK_FILE})

    if [ ${NEXT_UPDATE} -le ${NOW} ]; then
      PROVISION_REQUIRED=1
    fi
fi

if [ ${PROVISION_REQUIRED} -gt 0 ]; then
    echo "Update apt cache"
    apt-get -qq -y update > /dev/null
fi

if [ ${PROVISION_REQUIRED} -gt 1 ]; then
    echo "Installing basic requirements"
    SOFTWARE_PROPERTIES=$(dpkg -S /usr/bin/add-apt-repository|cut -d':' -f1)
    apt-get -qq -y install "$SOFTWARE_PROPERTIES" python3 python3-pip python3-apt python3-mysqldb python-mysqldb aptitude > /dev/null
fi

if [ ${PROVISION_REQUIRED} -gt 0 ]; then
    date --date="00:00:00 tomorrow" +%s > ${CHECK_FILE}
fi
