---
- name: "Install Apache web-server"
  apt:
    name: apache2

- name: "Change group for {{ ssh_user }}"
  user:
    name: "{{ ssh_user }}"
    group: www-data
    append: yes
    groups: [ "{{ ssh_user }}" ]

- name: "Force IPv4 binding"
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: "^Listen "
    insertafter: "^#Listen "
    line: "Listen {{vm_ip}}:80"
