---
- name: "Set-up main vhost"
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ hostname }}
  notify: restart apache

- file:
    path: /srv/{{ hostname }}
    state: absent
  when:
    - useSahredFolder
    - vhostSharedFolder is defined

- name: "Create docroot"
  file:
    path: /srv/{{ hostname }}/{{ docroot }}
    owner: www-data
    group: www-data
    mode: 0775
    state: directory
  when: not useSahredFolder or vhostSharedFolder is undefined

- name: "Symlink to shared folder"
  file:
    dest: /srv/{{ hostname }}
    src: "{{ vhostSharedFolder }}"
    state: link
  when:
    - useSahredFolder
    - vhostSharedFolder is defined

- name: "Disable default VHost"
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache

- name: "Enable VHost"
  file:
    src: /etc/apache2/sites-available/{{ hostname }}
    dest: /etc/apache2/sites-enabled/000-{{ hostname }}.conf
    state: link
  notify: restart apache
