- name: 'Add "WebUpd8" Team Java PPA'
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: "Accept Oracle license"
  debconf:
    name: 'oracle-java8-installer'
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: select

- name: "Install Java 8"
  apt:
    name: 'oracle-java8-installer'
    state: installed

- name: "Set default Java"
  apt:
    name: 'oracle-java8-set-default'
    state: installed

