---
- name: Set timezone
  timezone:
    name: Europe/Berlin

- name: "Set UMASK for pam_umask to 002"
  lineinfile:
    path: /etc/login.defs
    regexp: '^(UMASK)\s+022$'
    line: '\1 002'
    backrefs: yes

- name: "Change user group"
  user:
    name: "{{ ansible_ssh_user }}"
    group: "www-data"
    groups:
      - "{{ ansible_ssh_user }}"
      - "www-data"
      - "adm"
      - "audio"
      - "cdrom"
      - "dialout"
      - "dip"
      - "floppy"
      - "lxd"
      - "netdev"
      - "plugdev"
      - "sudo"
      - "video"

- name: "Ensure locale is generated"
  locale_gen:
    name: "de_DE.UTF-8"
    state: present
