---
- name: "Restart Head application"
  systemd:
    name: es-head
    state: restarted
  listen: restart es-head

- name: "Restart nginx"
  service:
    name: nginx
    state: restarted
  listen: restart nginx

- name: "Restart apache"
  service:
    name: apache2
    state: restarted
  listen: "restart apache"
