- name: "Install analysis-icu plugin"
  elasticsearch_plugin:
    name: "analysis-icu"
  notify: restart elasticsearch

- name: "Install decompound plugin"
  command: "/usr/share/elasticsearch/bin/plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-decompound/{{elasticsearch.version}}.0/elasticsearch-analysis-decompound-{{elasticsearch.version}}.0-plugin.zip"
  args:
    creates: "/usr/share/elasticsearch/plugins/decompound/"
  notify: restart elasticsearch
  when:
    - elasticsearch.version is version_compare('6.0', '<')

- name: "Enable Elasticsearch at boot time"
  systemd:
    name: 'elasticsearch'
    enabled: yes
    state: started
    daemon_reload: yes
  notify: restart elasticsearch
