- name: "Install analysis-icu plugin"
  elasticsearch_plugin:
    name: "analysis-icu"
  notify: restart elasticsearch

- name: "Install decompound plugin"
  elasticsearch_plugin:
    name: "http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-decompound/{{elasticsearch.version}}.0/elasticsearch-analysis-decompound-{{elasticsearch.version}}.0-plugin.zip"
  notify: restart elasticsearch
  when:
    - elasticsearch.version|version_compare('6.0', '<')

- name: "Enable Elasticsearch at boot time"
  service:
    name: 'elasticsearch'
    enabled: yes
  notify: restart elasticsearch
