- name: Download Ioncube Loader
  unarchive:
    creates: /tmp/ioncube
    src: https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Create ioncube dir
  file:
    path: /opt/ioncube
    state: directory

- name: Copy Ioncube Loader to PHP extensions dir
  copy:
    src: /tmp/ioncube/ioncube_loader_lin_{{ php.version }}.so
    dest: /opt/ioncube/
    remote_src: yes

- name: Create Ioncube config
  template:
    src: ioncube.ini.j2
    dest: /etc/php/{{ php.version }}/mods-available/ioncube.ini

- name: Activating Ioncube Loader
  shell: phpenmod -s ALL -v {{ php.version }} ioncube
  notify: restart apache

