- name: "Create directory for Elasticsearch HEAD application"
  file:
    path: "/opt/elasticsearch-head"
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: "Download and extract Elasticsearch HEAD application"
  unarchive:
    src: "https://github.com/mobz/elasticsearch-head/archive/master.tar.gz"
    dest: "/opt/elasticsearch-head"
    remote_src: yes
    extra_opts: ['--strip-components=1']

- name: "Change group and owner for Elasticsearch HEAD"
  file:
    path: "/opt/elasticsearch-head"
    state: directory
    owner: ubuntu
    group: ubuntu

- name: "Install dependencies"
  shell: npm i
  args:
    chdir: "/opt/elasticsearch-head/"
    creates: "/opt/elasticsearch-head/node_modules/"

- name: "Creating systemd service"
  template:
    src: es-head.service.j2
    dest: "/lib/systemd/system/es-head.service"

- name: "Restart Head application"
  systemd:
    name: es-head
    state: started
    daemon_reload: yes
    enabled: yes

- name: "Replace default ES host"
  replace:
    path: "/opt/elasticsearch-head/_site/app.js"
    regexp: "localhost:9200"
    replace: "{{ hostname }}:9200"
  notify: restart es-head
