
- name: "Include standalone elasticsearch-head tasks"
  include_tasks: head.yml

- name: "Include nginx-proxy tasks"
  include_tasks: nginx.yml
  when: not elastic_is_on_web_node

- name: "Include apache-proxy tasks"
  include_tasks: apache-vhost.yml
  when: elastic_is_on_web_node
