- name: "Add nodejs apt key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

- name: "Add nodejs repository"
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x xenial main"

- name: "Install nodejs"
  apt:
    name: "nodejs"
    state: installed
