---
- name: "Install PHP {{ php.version }}"
  apt:
    name:
      - "php{{ php.version }}"
      - "php{{ php.version }}-bcmath"
      - "php{{ php.version }}-bz2"
      - "php{{ php.version }}-cli"
      - "php{{ php.version }}-curl"
      - "php{{ php.version }}-dev"
      - "php{{ php.version }}-fileinfo"
      - "php{{ php.version }}-gd"
      - "php{{ php.version }}-gmagick"
      - "php{{ php.version }}-iconv"
      - "php{{ php.version }}-intl"
      - "php{{ php.version }}-json"
      - "php{{ php.version }}-mbstring"
      - "php{{ php.version }}-mysql"
      - "php{{ php.version }}-opcache"
      - "php{{ php.version }}-pdo"
      - "php{{ php.version }}-pdo-mysql"
      - "php{{ php.version }}-phar"
      - "php{{ php.version }}-posix"
      - "php{{ php.version }}-recode"
      - "php{{ php.version }}-sockets"
      - "php-sodium"
      - "php{{ php.version }}-tokenizer"
      - "php{{ php.version }}-xdebug"
      - "php{{ php.version }}-xml"
      - "php{{ php.version }}-xmlreader"
      - "php{{ php.version }}-xmlwriter"
      - "php{{ php.version }}-xsl"
      - "php{{ php.version }}-yaml"
      - "php{{ php.version }}-zip"
    state: present
  notify: restart apache

- name: "Install additional PHP extensions"
  apt:
    name: "{{php.extensions}}"
    state: present
  when: php.extensions is defined
  notify: restart apache

- name: "Write custom PHP config"
  template:
    src: php-custom.ini.j2
    dest: /etc/php/{{ php.version }}/mods-available/custom.ini
  notify: restart apache

- name: "Enable custom PHP config"
  command: "/usr/sbin/phpenmod -v {{ php.version }} -s ALL custom"
  args:
    creates: "/etc/php/{{ php.version }}/apache2/conf.d/85-custom.ini"
  notify: restart apache

- name: "Create 'xdebug' alias"
  lineinfile:
    path: "/home/{{ ssh_user }}/.bash_aliases"
    regexp: '^alias xdebug='
    line: "alias xdebug='XDEBUG_CONFIG=\"idekey=42\" PHP_IDE_CONFIG=\"serverName={{ hostname }}\" php'"
    create: true
    owner: "{{ ssh_user }}"

- name: "Update alternatives"
  alternatives:
    name: php
    path: "/usr/bin/php{{ php.version }}"
