- name: "Enabling Apache Module: ssl"
  apache2_module:
    name: ssl
    state: present

- name: "Enabling Apache Module: proxy"
  apache2_module:
    name: proxy
    state: present

- name: "Enabling Apache Module: proxy_http"
  apache2_module:
    name: proxy_http
    state: present

- name: "Enabling Apache Module: proxy_html"
  apache2_module:
    name: proxy_html
    state: present


- name: "Adding proxies"
  template:
    src: apache-vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ hostname }}-proxies
  notify: restart apache
  when: proxies is defined

- name: "Enable VHost"
  file:
    src: /etc/apache2/sites-available/{{ hostname }}-proxies
    dest: /etc/apache2/sites-enabled/001-{{ hostname }}-proxies.conf
    state: link
  notify: restart apache
  when: proxies is defined
