---
- hosts: all
  roles:
    - { role: swapfile, swapfile_location: /tmp/swapfile, swapfile_size: "{{4096 - vm.memory}}M", swapfile_swappiness: 10, when: is_single_node_mode and vm.memory < 4096 }
    - common

- hosts: web
  roles:
    - common-web
    - apache
    - php
    - mysql-client

- hosts: database
  roles:
    - mysql-client
    - mysql-server

- hosts: elasticsearch
  roles:
    - { role: swapfile, swapfile_location: /tmp/swapfile, swapfile_size: "{{vm.memory}}M", swapfile_swappiness: 10, when: not is_single_node_mode }
    - java
    - head-standalone
    - elasticsearch
