---
- hosts: all
  roles:
    - { role: swapfile, swapfile_location: /tmp/swapfile, swapfile_size: "{{vm.memory}}M", swapfile_swappiness: 10, when: is_single_node_mode and vm.memory < 4096 }
    - common

- hosts: web
  roles:
    - common-web
    - apache
    - php
    - mysql-client

- hosts: database
  roles:
    - mysql-client
    - mysql-server

- hosts: elasticsearch
  roles:
    - { role: swapfile, swapfile_location: /tmp/swapfile, swapfile_size: "{{vm.memory}}M", swapfile_swappiness: 10, when: not is_single_node_mode }
    - java
    - nodejs
    - head-standalone
    - elasticsearch

- hosts: java
  roles:
    - java

- hosts: nodejs
  roles:
    - nodejs

- hosts: oxid
  roles:
    - oxid

- hosts: e-mail
  roles:
    - mailcatcher
  vars:
    mailcatcher_options:
      ip: 0.0.0.0
      smtp-port: 1025
      http-port: 1080
    mailcatcher_user: root
    mailcatcher_group: root
    mailcatcher_groups: ["root"]
