- name: "Check if DB exists"
  shell: "mysql -sNe 'SHOW DATABASES'|grep {{ db.key }}"
  register: db_status
  failed_when: db_status.rc == 2

- name: "Importing dump file(s) for database"
  mysql_db:
    target: "{{config_path}}/{{item}}"
    name: "{{db.key}}"
    state: import
  with_items: "{{db.value}}"
  when: db_status.rc is defined and db_status.rc == 1
