- name: "Check if DB exists"
  shell: "mysql -NBAse 'SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = \"{{ db.key }}\"'"
  register: db_status

- name: "Importing dump file(s) for database"
  mysql_db:
    target: "{{config_path}}/{{item}}"
    name: "{{db.key}}"
    state: import
  with_items: "{{db.value}}"
  when: db_status.stdout|trim|int == 0
